In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [3]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
print(arr1.ndim)
print(arr2.ndim)
print(arr1.shape)
print(arr2.shape)
print(arr1.size)
print(arr2.size)
print(arr1.dtype)
print(arr2.dtype)

1
2
(3,)
(2, 3)
3
6
int64
int64


In [5]:
arr_all_0 = np.zeros(6)
arr_all_0

array([0., 0., 0., 0., 0., 0.])

In [6]:
arr_all_1 = np.ones(6)
arr_all_1

array([1., 1., 1., 1., 1., 1.])

In [7]:
arr_even = np.arange(10,22,2)
arr_even

array([10, 12, 14, 16, 18, 20])

In [8]:
arr1 = np.array([1,3,2,4,9])

In [9]:
arr1

array([1, 3, 2, 4, 9])

In [10]:
arr2 = np.ones(5)

In [11]:
arr2

array([1., 1., 1., 1., 1.])

In [12]:
arr3 = np.zeros(3)

In [13]:
arr3

array([0., 0., 0.])

In [14]:
arr4 = np.concatenate([arr1,arr2,arr3])

In [19]:
arr4

array([1., 3., 2., 4., 9., 1., 1., 1., 1., 1., 0., 0., 0.])

In [21]:
arr1.sort()

In [22]:
arr1

array([1, 2, 3, 4, 9])

In [23]:
print(arr1[-3])
print(arr1[2])

3
3


In [25]:
print(arr1[1:4])

[2 3 4]


In [26]:
arr1+arr2

array([ 2.,  3.,  4.,  5., 10.])

In [27]:
arr1*(-5)

array([ -5, -10, -15, -20, -45])

In [29]:
print(arr1.max())
print(arr1.min())
print(arr1.sum())
print(arr1.mean())

9
1
19
3.8


In [31]:
arr1[(arr1<1)|(arr1>3)]

array([4, 9])